name: Checkmarx Scan

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: ast-scanner-plugin
          base_uri: https://ast-master.dev.cxast.net/
          cx_tenant: organization
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --tags galactica-team