name: Checkmarx CxGo Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: ${{ github.event.repository.name }}
        team: ${{ secrets.CXGO_TEAM }}
        cxgo_client_secret: ${{ secrets.CX_GO_CLIENT_SECRET }}
        cxgo_base_url: https://api.checkmarx.net
        cxgo_portal_url: https://cloud.checkmarx.net
        break_build: true
        scanners: cxgo
        bug_tracker: GITHUBPULL
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }}