name: Create Draft Release
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Create Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token}}

      - name: Create Draft Release
        id: draf_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload artifact and release
        uses: nanoufo/action-upload-artifacts-and-release-assets@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          path: |
            ./target/checkmarx-ast-scanner.hpi
            LICENSE.md
          upload-release-files: true
          release-upload-url: ${{ steps.draf_release.outputs.upload_url }}