
name: Version by User Input 

on:
  workflow_dispatch:
      inputs:
         version:
            description: 'Next release version'
            required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Create new release Tag
        run: git tag ${{ github.event.inputs.version }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml -DskipTests -DVERSION_CMD=${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token}}
      - name: Create Draft Release
        id: draf_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          
      - name: Create Release
        id: create_release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          github_token: ${{ secrets.PAT }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/checkmarx-ast-scanner.hpi
          asset_name: checkmarx-ast-scanner.hpi
          asset_content_type: application/multipart-core
          overwrite: true
      - name: Push the tag 
        run: git push origin ${{ github.event.inputs.version }}
